---
- name: "Ensure {{ template_root }} exists"
  file:
    path: "{{ item }}"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    state: directory
  with_items:
    - "{{ template_root }}"
    - "{{ template_root }}/{{ template_path | dirname }}"
  tags:
    - config
    - template

- name: "Template the config file"
  template:
    src: "{{ template_path }}"
    dest: "{{ template_root }}/{{ template_path }}"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    mode: "u=rwx"
  tags:
    - config
    - template
